version: '3.4'

services:
  backend:
    image: theapp
    build: ./app
      # context: .
      # dockerfile: ./Dockerfile
    # command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.main:app --host 0.0.0.0 --port 8000"]
    command: uvicorn main:app --host 0.0.0.0 --port 5001 --reload
    # to run docker compose in attached mode: docker-compose -f "docker-compose.debug.yml" up
    environment:
      - DEBUG:1
    volumes:
      - ./app:/app
    restart: on-failure
    ports:
      - 5001:5001
      - 5678:5678
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - './frontend:/app'
      # - '/app/node_modules'
    ports:
      - 8080:8080
  
  db:
    image: postgres:13
    expose:
      - 5432
    environment:
      - POSTGRES_USER=ttadmin
      - POSTGRES_PASSWORD=ttadmin
      - POSTGRES_DB=ttadmin_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data: